[build]
  publish = "build"                # Adjust according to your build output
  command = "npm run build"        # Adjust according to your build script
  functions = "functions"

[functions]
  directory = "netlify/functions"  # Directory for serverless functions

[dev]
  command = "node server.js"          # Command for local development
  port = 3030                      # Optional development port

[environment]
  NODE_ENV = "production"          # Example to set environment variables
